name: Pull request Check / Lint

on: [push]
  
jobs:
  Lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.8.1]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.JS ${{ matrix.nove-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nove-version }}
      - name: Install deps
        run: npm install
      - name: Run Eslint
        run: npm run lint
      - name: Run Type-check
        run: npm run type-check
